### ISSUE TITLE
Where is the https://material.io/components site repository?

### ISSUE THREAD

**Issue by AzimMuradov** [material-components/material-components#101]
Where is the https://material.io/components **site** repository? (I need to PR some changes to the site)

I only found [this](https://github.com/material-admin/doc-material-components) repo, but it seems outdated.

**Comment by tonyhallett** [comment]
https://github.com/material-components/material-components-web
https://github.com/material-components/material-components-android
...

https://github.com/material-components/material-components-site-generator
