### ISSUE TITLE
Looking for m3 docs repo

### ISSUE THREAD

**Issue by tonyhallett** [material-components/material-components#104]
There is a docs issue on this page https://m3.material.io/styles/typography/tokens

![image](https://user-images.githubusercontent.com/11292998/152997059-b47b6fcd-9cd0-4a8e-8c2e-3ca64275a77d.png)

Should be 500 instead of Roboto Medium for md.sys.typescale.body-small.weight

Can someone point me to the repo - nothing in the page source.  Github link at the bottom of the page https://www.github.com/material-components

**Comment by leticiarossi** [comment]
This has been fixed in https://m3.material.io/styles/typography/type-scale-tokens
