### ISSUE TITLE
M3 docs on typograph section, tokens tab is bugged

### ISSUE THREAD

**Issue by katriellucas** [material-components/material-components#105]
The layout on this page: https://m3.material.io/styles/typography/tokens, is very weird, please take a look on the image below:

![image](https://user-images.githubusercontent.com/54755295/154854244-0bbbbb36-35d2-4296-ba6b-af6ce4783b06.png)

**Comment by leticiarossi** [comment]
This has been fixed in https://m3.material.io/styles/typography/type-scale-tokens#40fc37f8-3269-4aa3-9f28-c6113079ac5d
