### ISSUE TITLE
[Docs] Material Motion Easings are Documented using a Deprecated Format

### ISSUE THREAD

**Issue by Char2sGu** [material-components/material-components#106]
At https://material.io/design/motion/the-motion-system.html, the "easing" specs are documented as "40% Outgoing Only", "80% Incoming Only", "80% Incoming, 40% Outgoing" and so on:

![image](https://user-images.githubusercontent.com/63489409/166024517-a8878766-e510-45e1-a5ff-c3616c62d4e4.png)

I can only find the definition of these easings in the [archived documents](https://material.io/archive/guidelines/motion/duration-easing.html#duration-easing-natural-easing-curves):

![image](https://user-images.githubusercontent.com/63489409/166048224-c03bdd09-8a07-400f-ac23-ff8be3a8acef.png)

The current document didn't mention these concepts at all:

![image](https://user-images.githubusercontent.com/63489409/166053859-f61e2ca7-65c8-491f-b119-20067a7d7ba6.png)

I think it's better to update these concepts to match the current documents?

**Comment by leticiarossi** [comment]
Please see updated guidelines https://m3.material.io/styles/motion/overview
