### ISSUE TITLE
M3 site navigation seems broken on Chrome

### ISSUE THREAD

**Issue by m-melis** [material-components/material-components#107]
As shown below, https://m3.material.io/ appears broken to me on Chrome, Version 101.0.4951.67, Windows 10. Works fine on other browsers. Tried hard-refreshing, clearing cache and more.

![image](https://user-images.githubusercontent.com/7879584/168250425-045ffc02-1037-491c-b67f-54c274392594.png)

**Comment by leticiarossi** [comment]
Hi, will close this since it's been a while this was reported, but if you're still having issues as of today please feel free to reopen.
