### ISSUE TITLE
[TopAppBar] drop shadow

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components#108]
It says "Elevation: No drop shadow", but the TopAppBar casts a drop shadow.
https://m3.material.io/components/top-app-bar/overview
![unnamed](https://user-images.githubusercontent.com/71050561/179908890-1221fd7e-1314-4a39-a837-42c392941ecc.png)

**Comment by leticiarossi** [comment]
Looks like the images have been updated!
