### ISSUE TITLE
Navigation bar should hide on scroll down

### ISSUE THREAD

**Issue by Whip** [material-components/material-components#111]
On the [Guidelines](https://m3.material.io/components/navigation-bar/guidelines#bd6c5e81-4699-4652-9e3a-b03aa97b8b4b) page of navigation bar, there's a section titled **Scrolling**. It says the navigation bar shows when scrolling down and hides when scrolling up. I think this is a mistake, it should show when scrolling up and hide on scrolling down. This is how the [Bottom app bar](https://m3.material.io/components/bottom-app-bar/guidelines#833a0c24-f54b-436b-941e-f9346e47cd84) functions.

Also, in the new Gmail function, the navigation bar does hide on scroll down and reveals on scroll up so I think the guidelines has got it wrong here.

**Comment by leticiarossi** [comment]
The wording has been updated since this issue was created!
