### ISSUE TITLE
Slider height is inconsistent

### ISSUE THREAD

**Issue by Whip** [material-components/material-components#112]
The height of the slider is mentioned as 6dp in one place and 4dp in another. Please clarify.

![137](https://user-images.githubusercontent.com/11595460/194742593-f3c31607-e5cf-4520-b6f8-54e6bde8d302.jpg)
![138](https://user-images.githubusercontent.com/11595460/194742598-de756f2b-35eb-4481-bbf1-6bb57caf456f.jpg)

**Comment by pekingme** [comment]
The height of the track is 4dp. This seems like a bug on m3.material.io. I'll file a bug internally to update. Thanks for reporting. Closing this issue.
