### ISSUE TITLE
[Elevation] Level 3 is not 5dp

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components#114]
Level 3 (md.sys.elevation.level3) is not 5dp but 6dp (the figure is wrong).
https://m3.material.io/styles/elevation/applying-elevation:
![unnamed (1)](https://user-images.githubusercontent.com/71050561/197447098-b9e2749e-f5ca-42cc-8f8d-9470bfd617a4.png)

https://m3.material.io/styles/elevation/tokens:
```
Role    | System token            | Value
Level 3	| md.sys.elevation.level3 | 6dp
```

**Comment by pekingme** [comment]
Good catch, thanks for reporting! Will let the material.io team know. Closing the issue.
