### ISSUE TITLE
Web Components docs mistakes - wrong colors.

### ISSUE THREAD

**Issue by veritymedia** [material-components/material-components#115]
### Overview
The color token referenced for the common [button component (filled) ](https://m3.material.io/components/buttons/specs#87fc1729-0e9a-412d-af1d-4f2290904a0f) hover state seems wrong.

The visual of the button clearly shows that the text should be highly contrasting to the container color.
![image](https://user-images.githubusercontent.com/64927690/215294031-143bdf52-390e-498b-a077-298cdc36b309.png)

But, the spec says that we should use the same token for both the text and the container. 
![image](https://user-images.githubusercontent.com/64927690/215324110-1b47848d-55d7-4c60-ac0e-093a649a2ad4.png)

This seems wrong to me.

There maybe more of such cases.

Edit: Just checked and all of the buttons seem affected. The normal variant is correct - specifies contrasting colors, but each of the hover, disabled, focused and pressed state variants all give the same color for the background and content.

### Reproduction steps
Not applicable

### Version number
Not applicable

### Operating system and device
Not applicable

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by leticiarossi** [comment]
That is due to the opacity layer of the state layer color not being 100%, so visually they end up being different colors. the website has been updated since this issue was filled and has more details now, like the state layer opacity
