### ISSUE TITLE
Why M3 dialog full screen close icon is not left aligned.

### ISSUE THREAD

**Issue by sxhuan** [material-components/material-components#116]
### Overview
The M2 design dialog full-screen close icon seems to be left aligned, what's the reason for the change in M3?

### Version number
M3 Design

- - -

## Useful Links
https://m3.material.io/components/dialogs/specs#307347a6-ad90-4c63-bdec-06680c9ae433

**Comment by leticiarossi** [comment]
Current specs show the close button of the full-screen dialog on the left as well! https://m3.material.io/components/dialogs/specs#bbf1acde-f8d2-4ae1-9d51-343e96c4ac20
