### ISSUE TITLE
M3 top app bar colors

### ISSUE THREAD

**Issue by mobilekosmos** [material-components/material-components#120]
[https://m3.material.io/components/top-app-bar/specs#1b87ea47-fae2-4beb-aeb0-8d448afa55c8](https://m3.material.io/components/top-app-bar/specs#1b87ea47-fae2-4beb-aeb0-8d448afa55c8)

According to the docs the back button should have the color onSurface, and the right icons the color onSurfaceVariant. These are also the default colors applied when using Jetpack Compose, but in the screenshot on the linked website above all icons have the same color.

**Comment by leticiarossi** [comment]
It looks like the colors have been updated on the screenshot and it's following the specs
