### ISSUE TITLE
hard to read in dark theme

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components#121]
Some text in https://m3.material.io/styles/color/the-color-system/color-roles is hard to read in the dark theme.
![a](https://github.com/material-components/material-components/assets/71050561/7e7353d9-d172-415d-aaa2-10d1d358c31c)

![b](https://github.com/material-components/material-components/assets/71050561/49f47657-f465-46ed-9e7c-1cfc2cb6aada)

**Comment by leticiarossi** [comment]
Thank you, it looks like there have been some updates but there are still some issues in https://m3.material.io/styles/color/roles. I've reported it internally to be fixed.
