### ISSUE TITLE
404 page on selecting How dynamic color works link

### ISSUE THREAD

**Issue by msarkrish** [material-components/material-components#122]
### Issue Description

Selecting how dynamic color works showing a 404 page.

![image](https://github.com/material-components/material-components/assets/45334931/c8bc8aef-1f7a-49a0-aeb7-3fec198544ab)
![image](https://github.com/material-components/material-components/assets/45334931/fb0c267f-15b4-4b32-8aa0-9a362a69c239)

### Reproduction steps
 - Open this [link](https://m3.material.io/m3/pages/color/how-the-system-works) and tap on hyperlink of how dynamic color works.

**Comment by leticiarossi** [comment]
Looks like this was fixed and points to: https://m3.material.io/styles/color/system/how-the-system-works
