### ISSUE TITLE
specs are inconsistent

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components#123]
The specs are inconsistent in https://m3.material.io/components/switch/specs:
Switch unselected track color
- md.sys.color.surface-container-highest
![a](https://github.com/material-components/material-components/assets/71050561/9b84724d-49a1-45e7-9ea2-128325d174cb)
- Surface variant
![b](https://github.com/material-components/material-components/assets/71050561/00b8a00f-d3e6-4398-a495-e7159a691b54)

**Comment by uthidata** [comment]
It is fixed now.
