### ISSUE TITLE
Same issue here cannot reach the material.io website

### ISSUE THREAD

**Issue by AVidhanR** [material-components/material-components#124]
## Well, for now i'm using a proxy network to access it. Man that's pathetic.

**Comment by leticiarossi** [comment]
There are no current issues with the https://m3.material.io/ link, if you're still having issues please reopen with more information. Thanks!

**Comment by leticiarossi** [comment]
ah just saw this other issue https://github.com/material-components/material-components/issues/36 will leave this one closed as duplicated

**Comment by AVidhanR** [comment]
> There are no current issues with the https://m3.material.io/ link, if you're still having issues please reopen with more information. Thanks!

I got the solution, the website is not opening when I am using my own wifi network but using mobile internet i CAN access it. I forgot to remove the issue 😅
