### ISSUE TITLE
Incorrect SSL certifcate

### ISSUE THREAD

**Issue by pablomayobre** [material-components/material-components#16]
The certificate delivered by material.io is not valid, after running a [Symantex Crypto Report](https://cryptoreport.websecurity.symantec.com/checker/#certChecker), I could determine that the certificate is not correctly installed. It also looks like the server may be vulnerable to Heartbleed, BEAST and Poodle attacks.

I've also had problems trying to access the site from non-browser means (Using Node.js https.get), reason being the "unverified first certificate".

**Comment by liquidx** [comment]
Thanks for pointing this out. We're going to investigate why the SSL certificate isn't installed correctly and will update when we resolve this.

**Comment by pablomayobre** [comment]
Thank you for replaying back! I'm glad I was of help 😃

**Comment by bradwilliford** [comment]
Made some changes and the issue appears to be resolved. [The tool](https://cryptoreport.websecurity.symantec.com/checker/) is now reporting the certificate is installed correctly. 

Clear your SSL cache and let us know if that resolves the problem for you.

Thanks for reporting!

**Comment by pablomayobre** [comment]
The issue is fixed, I can now GET any resource from [material.io](material.io) from Node.js or any other HTTPS client without problems with certificates, I'll close this now.
