### ISSUE TITLE
material.io: progressive image loading is too slow

### ISSUE THREAD

**Issue by vitaly-zdanevich** [material-components/material-components#31]
Please check my recording https://youtu.be/YhpUg3gAg90

My current location is country Belarus.

**Comment by ajsecord** [comment]
Hi Vitaly, thank you very much for reporting this—we have an internal issue tracking this at high priority and are working on a solution. 

Unfortunately we don't have an external issue tracking system for material.io, I'm going to close this for now.

Thanks again!

**Comment by ajsecord** [comment]
Actually, I'm going to keep this open until the internal issue is resolved. Internal issue 79249437 for tracking.

**Comment by leticiarossi** [comment]
This has been marked as fixed
