### ISSUE TITLE
[material.io] Text opacities are inconsistent

### ISSUE THREAD

**Issue by stof** [material-components/material-components#35]
https://material.io/design/color/text-legibility.html#text-backgrounds has multiple sections showing different opacities for the different categories of texts, but they are inconsistent in most of them:

- the text talks about 100% opacity
- the example on the right talks about 87% opacity

**Comment by leticiarossi** [comment]
Please see the current m3.material.io website https://m3.material.io/ and if you find any issues feel free to report a new issue!
