### ISSUE TITLE
[material.io] image is not displayed

### ISSUE THREAD

**Issue by MichaelTamm** [material-components/material-components#37]
### Overview

On the page [Annotating MDC Web for the Closure Compiler](https://material.io/develop/web/docs/closure-compiler/) in the section [MDC Web Type System](https://material.io/develop/web/docs/closure-compiler/#mdc-web-type-system) the image "MDC Web Type System UML(-like) diagram" is not displayed.

The reason seems to be the following error, which can be found in the developer console:

```
Refused to load the image 'https://docs.google.com/drawings/d/1mJBPiUkdFiXkU5A6kAdpZD5nXr6NkHIIW_vMNVdIvYY/pub?w=960&h=720' because it violates the following Content Security Policy directive: "img-src https://material.io flutter.github.io https://www.google-analytics.com https://stats.g.doubleclick.net 'self'"
```

Screenshot:
![screenshot](https://user-images.githubusercontent.com/86703/46223308-4b6df780-c353-11e8-996b-2d397162cc0b.png)

### Reproduction steps
Open https://material.io/develop/web/docs/closure-compiler/#mdc-web-type-system in a web browser.

### Operating system and device
Affected are all web browsers which support content security policy.
My browser is Chrome 67 on Linux

**Comment by leticiarossi** [comment]
This issue is probably obsolete. Please see https://github.com/material-components/material-web/blob/main/docs/theming/typography.md and  https://m3.material.io/styles/typography/overview for updated information
