### ISSUE TITLE
[material.io] "Send feedback" form does not work

### ISSUE THREAD

**Issue by MichaelTamm** [material-components/material-components#38]
### Overview

I wanted to report the issue #37 via the "Send feedback" form, which seems to be integrated on every page under https://material.io/develop/web/docs/ -- Unfortunately it did not work:

![screenshot](https://user-images.githubusercontent.com/86703/46223815-ad7b2c80-c354-11e8-98b9-228531634404.png)

I guess this is another content security policy issue.

### Reproduction steps
- Open the page https://material.io/develop/web/docs/closure-compiler/ in a web browser
- Click on the icon in the bottom left corner => the "Send feedback" form appears
- Write some text into the "Send feedback" form
- Click on the [SEND] button of the "Send feedback" form

### Operating system and device
My browser is Chrome 67 on Linux

**Comment by leticiarossi** [comment]
Please see the current m3.material.io website https://m3.material.io/ there's a feedback button at the button of the page, if that doesn't work feel free to report it again. If you have a platform-related issue feel free to report it on the [specific platform repo](https://github.com/material-components/material-components?tab=readme-ov-file#repos) instead
