### ISSUE TITLE
Icons in drawer are not aligned on website

### ISSUE THREAD

**Issue by saadismail** [material-components/material-components#50]
### Overview
First off, I know that this is not the right place but since there is no contact way provided on the website so making the issue here to get the attention.

The drawer of the website: https://material.io/tools/icons/ is not aligned properly on small-res PC devices (check screenshot):

![screenshot from 2019-01-26 23-07-35](https://user-images.githubusercontent.com/11972404/51791091-a0b1fc80-21bf-11e9-82f6-55cee8ccaec3.png)

**Comment by kfranqueiro** [comment]
Hi, can you let us know what browser / OS you're using (and if possible, the browser's dimensions), and if there are any other steps needed to reproduce? We can probably find the right place to track this issue, but the more information we have, the more likely it is to be resolved. Thanks!
