### ISSUE TITLE
Guidelines are inconsistent about number min of tabs for Bottom Navigation

### ISSUE THREAD

**Issue by hormesiel** [material-components/material-components#52]
The [design guideline "Understanding navigation"](https://material.io/design/navigation/understanding-navigation.html#lateral-navigation) contains a table that says that Bottom navigation bars should be used for ***2**-5 Top-level destinations* :

![image](https://user-images.githubusercontent.com/1585006/53964432-a91b2280-40ef-11e9-95b9-f3640bfe77ec.png)

However on the [documentation for the "Bottom navigation" component](https://material.io/design/components/bottom-navigation.html#usage), there's a clear example that says *Don’t use a bottom navigation bar for fewer than **three** destinations (use tabs instead)* :

![image](https://user-images.githubusercontent.com/1585006/53964630-ff886100-40ef-11e9-8124-e506526d00e2.png)

Also, under *Representing destinations* there's no mention of a case with **Two destinations**.

So it looks like the guideline table is wrong.

**Comment by willlarche** [comment]
Thanks for reporting! I've sent this on to the guidelines team. I'm going to close this ticket since they track things in an internal issue tracking system.

**Comment by mobilekosmos** [comment]
I wonder on what do you decide if 2 or 3. I mean based on what? Gmail is using the bottom bar for 2 items and it is just fine.
