### ISSUE TITLE
Banner component implementation for Flutter is incorrectly displayed

### ISSUE THREAD

**Issue by jul1u5** [material-components/material-components#53]
The [material.io](https://material.io/design/components/banners.html#implementation) site lists the implementation of `Banner` [component](https://material.io/design/components/banners.html#implementation) as available in Flutter. However, even though Flutter has a `Banner` [class](https://docs.flutter.io/flutter/widgets/Banner-class.html), they are completely different:

## material.io

![image](https://user-images.githubusercontent.com/8469822/54056330-6a24c400-41f8-11e9-91a6-710eabddbd0d.png)

## Flutter

![image](https://user-images.githubusercontent.com/8469822/54056418-a9531500-41f8-11e9-8167-2d97d834b431.png)

**Comment by stefan-kolb** [comment]
Implemented by https://github.com/flutter/flutter/pull/36880.

**Comment by willlarche** [comment]
This link will be updated in the next release of the site.
