### ISSUE TITLE
Icon "star" SVG files has merged layers

### ISSUE THREAD

**Issue by WesCooper** [material-components/material-components#54]
I'm not 100% sure where this request should live, but I just wanted to bring attention to what seems to be a slight oops on one of the icons SVG files.

When downloading the "star" icon from material.io/tools/icons if you select any other version besides the default "Filled" version (ie. "Outlined", "Rounded", "Two-Tone", or "Sharp") the layers in the SVG version seem to be merged or flattened and requires some surgery to dismantle the background / area layer from the actual star shape.

When you drop these files into a platform such as Figma they show up like the below screenshot. The default "Filled" is the leftmost and working down through the options on material.io they show as you look rightward respectively:
![withoutediting](https://user-images.githubusercontent.com/10385225/54468719-8386bc80-4772-11e9-8e35-8af8c8d33da4.png)

Looking at the layers of these SVGs you can see the issue:
![layers](https://user-images.githubusercontent.com/10385225/54468737-baf56900-4772-11e9-8333-102d5ba75e2e.png)

You can also see that the two-tone star icon actually has it's layers properly separated but the background/area layer at the bottom comes with a fill color which makes it also have a black box look when initially imported.

**Comment by leticiarossi** [comment]
This has been fixed, please see https://fonts.google.com/icons
