### ISSUE TITLE
[Tooltip] Font size for desktop web application is too small

### ISSUE THREAD

**Issue by atiris** [material-components/material-components#56]
### Overview
Recommended Tooltip font height 10 px [for desktop](<https://material.io/design/components/tooltips.html#spec>) is too small.

### Reproduction steps

1. Go to https://material.io/design/components/tooltips.html#spec
2. Ask for user feedback to read text within the tooltip using desktop settings.

### Version number
Actual design specification.  
I can not find any version number [on your site](<https://material.io/>) (Found in CHANGELOG.md ?)

### Actual behavior

I created web application for desktop that follows the material principles for tooltips. App users complain to me about a small and hard to read font.

### Expected behavior

The tooltip font is well readable for most users. Tooltip is presented visually mainly by frame and background, not by small (difficult to read) font.

### Screenshots

In [documentation](<https://material.io/design/components/tooltips.html#spec>).

### Operating system and device

Any, it is design specification request.

### Additional context

Please, if you have any study that confirms that the appropriate font size for the desktop tooltip is 10 px, can you refer me to it?

### Possible solution

Increase recommended font size, eliminate specific font size for tooltip, or set it in proportion to the basic font size.

### Related requests

The first time it was incorrectly [specified here](<https://github.com/material-components/material-components-web/issues/4723>), but this is a design / specification problem / bug.

**Comment by atiris** [comment]
Hi @ajsecord @willlarche  
Since I still do not know whether I have placed this request in the right place, I would like to ask you to know if it makes any sense to submit this request here.

I have this problem:  
The design-specified font for tooltips is very difficult to read for my customers. I use angular material, but in angular material repository don't want to change it because the font size is defined in the material design (site) and that's what they blindly follow, whether it's good or not for component users... So I consider it as a problem of design specification. However, just entering a requirement is a pretty challenging process for me. :disappointed: 

- Is there any other repository / person / organization where can I report this request and get any response?
- And it is even possible to modify something like font size?

Because until now I have not been able to find anyone who is able to comment on it relevantly. I see that design change is very cumbersome if it is even possible... But if discussion about this small modification takes more than half a year, it is useless to me.

**Comment by abhiomkar** [comment]
Thanks for the follow up! I've sent this to our design team.

While we're waiting for response from design on this, what's stopping you from overriding styles for tooltip with [Body 1 or Body 2 typescale](https://material-components.github.io/material-components-web-catalog/#/component/typography).

Thanks!

**Comment by atiris** [comment]
Thanks for the reply @abhiomkar  
If I remember well, the last time I tried to modify look this way, I changed the size of other (parent) components as well (and that wasn't my intention), I just wanted to improve the readability of the tooltip. However, I will certainly look at it again.

**Comment by leticiarossi** [comment]
Please see current/updated guidelines https://m3.material.io/components/tooltips/specs and if there's still an issue feel free to report it again
