### ISSUE TITLE
Poor mouse interaction with menus

### ISSUE THREAD

**Issue by ptolp** [material-components/material-components#57]
### Overview
The conventional interaction with menus and dropdown menus is that the user can press down the mouse button on the menu header, move the cursor and release the mouse button to select. This makes a lot of sense, it is efficient, fast and accurate. The interaction of the menus in Material is a step backwards with reduced usability - the user is forced to click, then wait for the transition animation, move the mouse and click again. The pause adds an additional mental effort as well.

I suggest experimenting with menus so that they open with mouse down, maybe also with a finger down on touch screens.

### Reproduction steps
Try any version of material menu component.

### Version number
Any

### Operating system and device
All

- - -

## Useful Links
https://material.io/design/components/menus.html

**Comment by leticiarossi** [comment]
This seems directed towards Material Web, please report it on its repo https://github.com/material-components/material-components-web if you'd still like to raise the issue. Thanks!
