### ISSUE TITLE
Rename Cards to Figures

### ISSUE THREAD

**Issue by ronnievsmith** [material-components/material-components#61]
Sufficient overlap exists between Google's Material UI Card component and HTML's `<figure>` and associated `<figcaption>` element to consider renaming Material UI Cards to Material UI Figures.

### [Material Cards](https://material.io/design/components/cards.html) 

> Cards contain content and actions about a single subject.

### [Material Cards Usage](https://material.io/design/components/cards.html#usage)

> **Contained**: A card is identifiable as a single, contained unit.
> **Independent**: A card can stand alone, without relying on surrounding elements for context.
> **Individual**: A card cannot merge with another card, or divide into multiple cards.

### [figure: The Figure with Optional Caption element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)
The HTML `<figure>` (Figure With Optional Caption) element represents self-contained content, potentially with an optional caption, which is specified using the (`<figcaption>`) element. The figure, its caption, and its contents are referenced as a single unit.

### [figure: Usage notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure#Usage_notes)

> - Usually a `<figure>` is an image, illustration, diagram, code snippet, etc., that is referenced in the main flow of a document, but that can be moved to another part of the document or to an appendix without affecting the main flow.
> - Being a sectioning root, the outline of the content of the `<figure>` element is excluded from the main outline of the document.
> - A caption can be associated with the `<figure>` element by inserting a `<figcaption>` inside it (as the first or the last child). The first `<figcaption>` element found in the figure is presented as the figure's caption.

**Comment by ddemaree** [comment]
Thanks for the feedback! I can see your logic, but there are key differences between figures and cards as noted in the usage notes you quoted:

> Usually a `<figure>` is an image, illustration, diagram, code snippet, etc., that is **referenced in the main flow of a document**

> Cards contain content **and actions** about a single subject.

Cards are often used as elements in a collection (such as in Google Photos' Assistant view, where each card represents a single photo suggestion), and can be used standalone without being referenced from some other part of a document.

Also, a card should either be fully interactive (where clicking/tapping its surface reveals more information about the subject of the card) or have one or more contextual actions related to its content. 

Though not all cards are necessarily figures, a figure can _also_ be a card, or vice versa. Cards are appropriate to represent a "mini" version of some other rich content, like a link or post preview with follow or like actions attached, which could be referenced as a figure by some text.

Does that make sense?

**Comment by ronnievsmith** [comment]
Not sure if `<figure>` elements require being referenced. Both `<figure>` and Card represent self-contained content and both allow interactivity. 

I understand that `.mdc-typography--display1` (different codebase) was changed to `.mdc-typography--headline1` to better align to the spec (e.g. `<h1>`). Changing `.mdc-card` to `.mdc-figure` could simplify usage.
