### ISSUE TITLE
AS Preview doesn't match TextInputLayout actual appearance on device

### ISSUE THREAD

**Issue by samcackett** [material-components/material-components#62]
### Overview
Problem
The layout preview in Android Studio doesn't match how the Material Components `TextInputLayout` actually appears on an Android device. It just displays a very simple layout with a grey baseline.

 - Screenshots/Video (if possible)
![image](https://user-images.githubusercontent.com/5948635/61225480-8a214280-a718-11e9-9a0f-bafa018e8ab0.png)

 - Stack trace (if possible)
N/A

### Reproduction steps
 - Add a `com.google.android.material.textfield.TextInputLayout` to any layout
 - Open the Android Studio layout preview

#### Expected
Looks the same as on a real device

#### Actual
Looks very basic (see screenshot) and nothing like the real Material component

### Version number
 - Found in 1.1.0-alpha07

### Operating system and device
Any, doesn't make a difference

### Related issues
Couldn't find any

**Comment by andrewoverton** [comment]
This should maybe be filed to [material-components-android](https://github.com/material-components/material-components-android)

**Comment by samcackett** [comment]
Thanks @andrewoverton I've moved it there.
