### ISSUE TITLE
Just a FYI of a small bug on the material.io

### ISSUE THREAD

**Issue by jmuzsik** [material-components/material-components#65]
This is simply about a minor bug found on material.io that caused me a bit of frustration/confusion. 

How to reproduce:

1. Go to icons section
2. Search for arrow_downward
3. Press to download said icon
4. Change icon to color of white
5. Look at it

It's not white, it's black. I wasted a little time thinking something was up with my cache or build process. So, just wanted to let you guys know of this problem on the site. I would of looked to fix it myself but could not find a repo.

**Comment by leticiarossi** [comment]
This has been fixed https://fonts.google.com/icons?selected=Material+Icons+Outlined:arrow_downward:&icon.query=arrow+downward&icon.set=Material+Icons
