### ISSUE TITLE
Search for "errors" results in links that do not provide expected content.

### ISSUE THREAD

**Issue by mousedownmike** [material-components/material-components#66]
### Overview
Searching for "errors" on material.io has a top result for [Errors - Patterns - Material Design](https://material.io/guidelines/patterns/errors.html).  Following that link just directs you to the main [Design](https://material.io/design/) page. 

### Reproduction steps
 - Go to https://material.io
 - Click the search (magnifying glass) icon in the top right of page.
 - Enter `errors` in the search bar and Enter/Return
 - Observe 10 matching results with "Errors - Patterns - Material Design" as the first.
 - Click the first link.
 - Observe the Design page is shown with no information on Errors.

### Version number
 - Observed August 2, 2019 17:37 UTC

### Operating system and device
 - Ubuntu 19.04
 - Chrome Browser

**Comment by subchild** [comment]
Thanks for reporting this. We'll look at correcting this behavior. For now, you can find guidance on Errors in the original version of the spec linked from this page: https://material.io/design/introduction/#principles

**Comment by leticiarossi** [comment]
Please see https://m3.material.io/search.html?q=errors
