### ISSUE TITLE
[Slider] Configurable Tracks

### ISSUE THREAD

**Issue by sophher** [material-components/material-components#76]
Hello,
first of, thank you for your great work on the material spec. It really makes our applications more usable.

I hope I came to the right place for this feature request / spec addition. 

### Problem
We have a use-case, where we want to make a slider from -100% to +100%, with the default value being 0.

The problem is, that the current [spec](https://material.io/components/sliders/#usage) only allows the "track" to start from the left, or from the right:
![grafik](https://user-images.githubusercontent.com/61269115/74919783-68352000-53cb-11ea-9771-3741c0a9d304.png)
![grafik](https://user-images.githubusercontent.com/61269115/74919927-9c104580-53cb-11ea-889a-b3f6a581375a.png)

### Idea
It would be nice, to make the "track" zero position configurable:
![grafik](https://user-images.githubusercontent.com/61269115/74919375-cf9ea000-53ca-11ea-9865-439ebff3a58b.png)

One could even imagine supporting switching the values for left/right reading languages.

**Comment by willlarche** [comment]
Hello! Official word from the Material Designers:

This is a reasonable behavior and you should feel free to build it into your applications! Since it's not a high-demand critical user journey, we will not be adding it into the article on Slider but that doesn't mean it's not ok to do.

Thank you for your submission!

**Comment by willlarche** [comment]
And thank you for your kind words!

**Comment by axos88** [comment]
I'm also in need of this functionality. I wouldn't say it's an edge case at all.
