### ISSUE TITLE
set Focus manually for select 

### ISSUE THREAD

**Issue by kamarajuPrathi** [material-components/material-components#77]
is there a way i can set set focus manually to the select ?

**Comment by leticiarossi** [comment]
Hi, for usage questions we encourage users to check our platform docs or ask on stackoverflow ([example](https://stackoverflow.com/questions/tagged/material-components-android)). If there's an issue with a specific platform please redirect your question there (see all [platforms repos links](https://github.com/material-components/material-components?tab=readme-ov-file#repos), or if it's about angular: https://github.com/angular/components/issues)
