### ISSUE TITLE
Latest Pixel devices missing from Device Metrics resource page

### ISSUE THREAD

**Issue by kkuan2011** [material-components/material-components#80]
### Overview
https://material.io/resources/devices/

I was trying to look up the device resolution of some of the newer Pixel phones, but only found the device metrics for the Pixel and Pixel XL devices. Would be good to add Pixel 2, 2XL, 3, 3XL, 3a, 3aXL, 4, and 4XL devices.

### Reproduction steps
Go to https://material.io/resources/devices/

**Comment by subchild** [comment]
Thanks for the comment. We have decided to deprecate the Device Metrics page (more on this very soon). 

Please see this post from our team for calculating device measurements:
https://medium.com/google-design/how-to-find-device-metrics-for-any-screen-62b9ad84d097

**Comment by kkuan2011** [comment]
Ah okay, thanks for the update and link to the post!
