### ISSUE TITLE
Material Icons Library 404 - Page Not Found

### ISSUE THREAD

**Issue by stephan-gruen** [material-components/material-components#90]
The Material Icons Library is gone.

[https://material.io/resources/icons](https://material.io/resources/icons) shows a 404 - Page Not Found

**Comment by WorldWideWebDev** [comment]
Seems to work for me,,, 
https://material.io/resources/icons/?style=baseline  [https://material.io/resources/icons/?style=baseline](url)

**Comment by stephan-gruen** [comment]
Yes, it works again.
