### ISSUE TITLE
[Guidelines/Android - menus] - Some example images are not showing

### ISSUE THREAD

**Issue by enricocid** [material-components/material-components#93]
**Bug**
Some example images are not showing properly in material.io website.

**To Reproduce**

1. Go to [**dropdown-menus**](https://material.io/components/menus/android#dropdown-menus)
2. Scroll down to **Context menus**

1. Go to [**dropdown-menus**](https://material.io/components/menus/android#dropdown-menus)
2. Scroll down to **Adding icons on popup menus**

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/7274841/103920252-58bce380-5111-11eb-8002-fa58818503ac.png)

Sorry if this is the wrong place to post this kind of issues :)

**Comment by leticiarossi** [comment]
Please see current docs https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md platform docs aren't displayed on the material3 website anymore
