### ISSUE TITLE
The svg version of the all_inbox image is broken.

### ISSUE THREAD

**Issue by Andromeda606** [material-components/material-components#94]
![image](https://user-images.githubusercontent.com/43077625/104118927-563ed180-533d-11eb-898b-94e98e765ac8.png)
![image](https://user-images.githubusercontent.com/43077625/104118930-5b038580-533d-11eb-90b6-f6608e9c4df6.png)

**Comment by Andromeda606** [comment]
whatshot Same mistake

**Comment by leticiarossi** [comment]
It's been fixed https://fonts.google.com/icons?icon.query=all+inbox&icon.platform=web&icon.style=Rounded&icon.set=Material+Icons there's also a different looking Material Symbol version which you can see by changing the style on the left!
