### ISSUE TITLE
Card elevation docs don't make sense?

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components#95]
1. Go to https://material.io/components/cards
2. Go to "Elevation" section

Read
"On mobile, a card’s default elevation is 1dp, with a raised dragged elevation of 8dp."

Right below that
"On desktop and mobile, cards can have a resting elevation of 0dp. They elevate to 4dp on hover."

So which one is it? Cards have resting or default elevation of 1 or 0?

**Comment by leticiarossi** [comment]
Please see current specs https://m3.material.io/components/cards/specs

for your original question, the default elevation is _set_ to a certain value, but it _can_ have other user/custom set values as that customization is supported by the code and/or recommended by the guidelines.

**Comment by ColtonIdle** [comment]
3 years later... but I appreciate the comment 😂 cheers
