### ISSUE TITLE
Guidelines for 24 hour time picker

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [material-components/material-components#96]
The official Material Guidelines is missing a guideline for a 24 hour time picker (all examples are 12 hours only):
https://material.io/components/time-pickers

A 24 hour picker is not just a special case of a 12 hour picker.
1. There are no 24-hour analog clocks in common usage with circular clock face and numbers 0-23. So the circular clock face metaphor 12 hour time picker is based on cannot be simply extended to 24 hours.
2. In recent Android Material Components release the time picker for 24 hours shows only the even hours (0, 2, 4, 6...) on the clock face which is confusing for the users.

For more details see the related Android issue:
https://github.com/material-components/material-components-android/issues/1450

**Comment by leticiarossi** [comment]
See https://m3.material.io/components/time-pickers/specs#533817dd-8590-4d07-af4d-3b61de924c5f
