### ISSUE TITLE
Duplicating uints in an example.

### ISSUE THREAD

**Issue by SobolevIlya** [material-components/material-components#97]
https://material.io/design/communication/data-visualization.html#dashboards

Has an example of dashboard with the screenshot:

![image](https://user-images.githubusercontent.com/59829512/119610342-841b4300-be12-11eb-9db9-9d9df7104124.png)

I think duplicating `GB`  4 times is WRONG. Please update recommendations if you agree.

I would write `Usage datails (GB)` and removed all `GB`s from the sheet.

**Comment by leticiarossi** [comment]
Closing this as obsolete, please see the current website https://m3.material.io/
